version: '3'

services:
  # this container will run Cypress test using built-in Electron browser
  e2e-electron:
    container_name: k-ruoka-e2e-electron
    build:
      context: .
      # args: 
      #   my_workdir: /e2e_electron
    command: "--browser electron --spec 'cypress/integration/000-basic/000_smoke_spec.ts'"

  # this container will run Cypress test using Chrome browser
  e2e-chrome:
    container_name: k-ruoka-e2e-chrome
    build:
      context: .
      # args: 
      #   my_workdir: /e2e_chrome
    command: "--browser chrome --spec 'cypress/integration/000-basic/000_smoke_spec.ts'"

  # this container will run Cypress test using Firefox browser
  # note that both Chrome and Firefox browsers were pre-installed in the Docker image
  e2e-firefox:
    container_name: k-ruoka-e2e-firefox
    build:
      context: .
      # args: 
      #   my_workdir: /e2e_firefox
    command: "--browser firefox --spec 'cypress/integration/000-basic/000_smoke_spec.ts'"